# Generated by Django 3.2.9 on 2021-12-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, null=True, verbose_name='Имя пользователя')),
                ('source', models.CharField(max_length=255, null=True, verbose_name='Источник')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('post_date', models.DateField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['post_date'],
            },
        ),
    ]
