# Generated by Django 3.2.9 on 2021-12-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='post_date',
            field=models.DateField(null=True, verbose_name='Дата публикации'),
        ),
    ]
